---

dependency:
  name: galaxy

driver:
  name: vagrant
  provider:
    name: virtualbox

lint: |
  set -e .
  yamllint .
  ansible-lint

platforms:
  - name: mariadb-ubuntu
    box: ubuntu/focal64
    interfaces:
      - auto_config: true
        ip: 192.168.56.7
        netmask: 24
        network_name: private_network
  - name: mariadb-debian
    box: debian/buster64
    interfaces:
      - auto_config: true
        ip: 192.168.56.8
        netmask: 24
        network_name: private_network

provisioner:
  name: ansible
  lint:
    name: ansible-lint

scenario:
  name: default

verifier:
  name: ansible
