---

- name: Verify
  hosts: all
  become: true
  tasks:
  - name: (check) Test if MariaDB service is up
    shell: "systemctl status mariadb.service"
    changed_when: false

  - name: (check) Test if MariaDB port is open and reachable
    shell: "ss -ntlp4 | grep mariadb"
    changed_when: false

  - name: (check) Test if MariaDB can handle requests
    shell: "mysql -h localhost -e 'SELECT 1;'"
    changed_when: false
