---

- name: Verify
  hosts: all
  become: true
  tasks:
  - name: (check) Test if MariaDB service is up
    systemd:
      enabled: true
      masked: false
      name: "mariadb"
      state: started

  - name: (check) Test if MariaDB port is open and reachable
    wait_for:
      port: 3306
      delay: 2

  - name: (check) Test if MariaDB can handle requests
    command: "mysql -h localhost -e 'SELECT 1;'"
    changed_when: false
